fix(redux): add `id` to the listing server initial state
Farfetch/blackout pull request #125
Opened 2022-01-14 12:45 UTC by nelsonleite

## Description

This adds the missing `id` property to the listing server initial state, letting it pass through.
This also separates the products' `serverInitialState` types for the sake of readability.

## Checklist

- [x] The commit message follows our guidelines
- [x] Tests for the respective changes have been added
- [ ] The code is commented, particularly in hard-to-understand areas
- [x] The labels and/or milestones were added

## Disclaimer

By sending us your contributions, you are agreeing that your contribution is made subject to the terms of our [Contributor Ownership Statement](https://github.com/Farfetch/.github/blob/master/COS.md)

2022-01-14 13:44 UTC, anapim requested changes

2022-01-14 13:44 UTC, anapim commented on packages/redux/src/products/serverInitialState/lists.ts
> +// import type { Model, StoreState } from '../../types';
Left over code?

2022-01-14 13:50 UTC, mindouro approved these changes

2022-01-14 15:58 UTC, nelsonleite commented on packages/redux/src/products/serverInitialState/lists.ts
> +// import type { Model, StoreState } from '../../types';
Oops 🙈

2022-01-14 17:17 UTC, nelsonleite commented on packages/client/src/products/types/listing.types.ts
> +  id: string;
My mistake, added this in the `sets.types` 🙈

2022-01-14 17:17 UTC, nelsonleite commented on packages/redux/src/products/serverInitialState/index.ts
> +  } as { model: ListingModel });
Reviewed all of this 💪

2022-01-17 09:27 UTC, anapim approved these changes

2022-01-17 16:24 UTC, ricardojmf approved these changes

2022-01-17 16:34 UTC, catarinacouto approved these changes

2022-01-17 17:39 UTC, merged