feat(core): add update and delete order item endpoints
Farfetch/blackout pull request #220
Opened 2022-03-11 10:45 UTC by ivomota

## Description

We have added 2 new endpoints for order items:
- Update order item (to update the quantity of the item in the checkout order)
- Delete order item (to delete an item from the checkout order)

### Dependencies

None.

## Checklist

- [x] The commit message follows our guidelines
- [x] Tests for the respective changes have been added
- [x] The code is commented, particularly in hard-to-understand areas
- [x] The labels and/or milestones were added

## Disclaimer

By sending us your contributions, you are agreeing that your contribution is made subject to the terms of our [Contributor Ownership Statement](https://github.com/Farfetch/.github/blob/master/COS.md)

2022-03-11 14:24 UTC, rc23 approved these changes

2022-03-11 15:15 UTC, jhairabreu approved these changes

2022-03-11 15:19 UTC, jhairabreu requested changes
Just checking: Don't you need to make changes to the store (selectors, reducers, etc) ?

2022-03-14 12:31 UTC, jhairabreu approved these changes

2022-03-16 12:00 UTC, rc23 approved these changes

2022-03-16 15:40 UTC, jhairabreu requested changes

2022-03-16 15:40 UTC, jhairabreu commented on packages/core/src/checkout/redux/actionTypes.js
> +/** Action type dispatched when the get order item request fails. */
when the `update` and not `get`.

same for the lines below

2022-03-16 15:41 UTC, jhairabreu approved these changes

2022-03-16 15:44 UTC, merged