chore: replace moxios with msw
Farfetch/blackout pull request #347
Opened 2022-06-13 14:30 UTC by jhairabreu

This replaces moxios with msw in all areas where moxios is being used.

## Description

### Dependencies

## Checklist

- [ ] The commit message follows our guidelines
- [ ] Tests for the respective changes have been added
- [ ] The code is commented, particularly in hard-to-understand areas
- [ ] The labels and/or milestones were added

## Disclaimer

By sending us your contributions, you are agreeing that your contribution is made subject to the terms of our [Contributor Ownership Statement](https://github.com/Farfetch/.github/blob/master/COS.md)

2022-06-27 08:41 UTC, giuliamml approved these changes

2022-06-27 19:40 UTC, dnamorim requested changes

2022-06-27 19:40 UTC, dnamorim commented on packages/client/src/products/__fixtures__/getProductGrouping.fixtures.ts
>      rest.get(path, async (req, res, ctx) =>
Missing underscore on first parameter
```suggestion
    rest.get(path, async (_req, res, ctx) =>
```

2022-06-28 09:49 UTC, jhairabreu commented on packages/client/src/products/__fixtures__/getProductGrouping.fixtures.ts
>      rest.get(path, async (req, res, ctx) =>
should be ok now. thanks 👍

2022-06-28 10:16 UTC, dnamorim approved these changes

2022-06-28 10:17 UTC, merged