feat: review users structure in clients
Farfetch/blackout pull request #374
Opened 2022-06-23 13:57 UTC by pedro-gbf

## Description

This rearranges the users area with subareas of the users domain.
* New folder structure on clients
* Renaming of most of the users clients to include the prefix
* Exporting refactored so devs can import the root with the area with all the clients instead of matching the entire folder path.
* Some types were wrong and were reviewed

BREAKING-CHANGE: The user clients names were changed, and the folder structure as well.

### Dependencies

None

## Checklist

- [x] The commit message follows our guidelines
- [x] Tests for the respective changes have been added
- [x] The code is commented, particularly in hard-to-understand areas
- [x] The labels and/or milestones were added

## Disclaimer

By sending us your contributions, you are agreeing that your contribution is made subject to the terms of our [Contributor Ownership Statement](https://github.com/Farfetch/.github/blob/master/COS.md)

2022-06-27 17:10 UTC, andreecosta approved these changes

2022-06-27 17:49 UTC, jhairabreu requested changes
Don't forget to add the "Breaking Change" indication in the commit message, as well as an example of "before" and "after" for those changes

2022-06-28 09:44 UTC, jpklzm approved these changes

2022-06-29 09:38 UTC, jhairabreu approved these changes

2022-06-29 10:23 UTC, merged