(WIP) chore: imports standardisation
Farfetch/blackout pull request #388
Opened 2022-07-01 08:54 UTC by giuliamml

## Description
Standardised imports for test files on the `/client` folder, following convention on Gitlab issue [#121](https://gitlab.fftech.info/fps/platform/box/issues/121)

### Dependencies

## Checklist

- [ ] The commit message follows our guidelines
- [ ] Tests for the respective changes have been added
- [ ] The code is commented, particularly in hard-to-understand areas
- [ ] The labels and/or milestones were added

## Disclaimer

By sending us your contributions, you are agreeing that your contribution is made subject to the terms of our [Contributor Ownership Statement](https://github.com/Farfetch/.github/blob/master/COS.md)

2022-07-01 09:09 UTC, jhairabreu requested changes

2022-07-01 09:09 UTC, jhairabreu commented on packages/client/src/addresses/__tests__/getAddress.test.ts
> +  const id = addressId;
same here

2022-07-01 09:09 UTC, jhairabreu commented on packages/client/src/addresses/__tests__/getPredictions.test.ts
> +  const response = mockPredictionsResponse;
same here

2022-07-01 09:30 UTC, jhairabreu requested changes

2022-07-01 09:30 UTC, jhairabreu commented on packages/client/src/checkout/__tests__/getCheckoutOrderCharge.test.ts
>    const chargeId = 'eb92d414-68de-496e-96db-a0c6582b74d4';
You can also move this `chargeId` to the fixtures file.

2022-07-01 09:30 UTC, jhairabreu commented on packages/client/src/checkout/__tests__/getDeliveryBundleUpgrades.test.ts
>    const deliveryBundleId = '3742-ds12-njnj-j21j';
You can also move this `deliveryBundleId` to the fixtures file.

2022-07-01 09:30 UTC, jhairabreu commented on packages/client/src/checkout/__tests__/getUpgradeItemDeliveryProvisioning.test.ts
>    const deliveryBundleId = '3742-ds12-njnj-j21j';
Same for this deliveryBundleId

2022-07-01 09:30 UTC, jhairabreu commented on packages/client/src/checkout/__tests__/patchCheckoutCompletePayment.test.ts
> +  const id = transactionId;
Use the `transactionId` directly

2022-07-01 09:30 UTC, jhairabreu commented on packages/client/src/checkout/__tests__/patchDeliveryBundleUpgrades.test.ts
>    const deliveryBundleId = '3742-ds12-njnj-j21j';
Same for this `deliveryBundleId`

2022-07-01 09:30 UTC, jhairabreu commented on packages/client/src/contents/__tests__/getContentTypes.test.ts
> +import { types } from 'tests/__fixtures__/contents';
You can use `types as response` so it becomes clearer and delete L16

2022-07-01 09:30 UTC, jhairabreu commented on packages/client/src/returns/__tests__/getReturnPickupRescheduleRequest.test.ts
> +  const id = mockReturnId;
Use the `mockReturnId` directly and remove this line.

2022-07-01 09:30 UTC, jhairabreu commented on packages/client/src/returns/__tests__/getReturnPickupRescheduleRequests.test.ts
> +  const id = mockReturnId;
Use the `mockReturnId` directly and remove this line.

2022-07-01 09:30 UTC, jhairabreu commented on packages/client/src/returns/__tests__/getReturnReferences.test.ts
> +  const id = mockReturnId;
Use the `mockReturnId` directly and remove this line.

2022-07-01 09:30 UTC, jhairabreu commented on packages/client/src/returns/__tests__/getReturnsFromOrder.test.ts
> +  const orderId = mockOrderId;
Use the `mockOrderId` directly and remove this line.

2022-07-04 15:51 UTC, jhairabreu approved these changes

2022-07-05 10:06 UTC, dnamorim requested changes

2022-07-05 10:17 UTC, giuliamml commented on packages/client/src/users/addresses/__tests__/postUserAddress.test.ts
> +import { address2, userId } from 'tests/__fixtures__/addresses';
yes, I think that makes sense. Will add the suggested change

2022-07-05 10:17 UTC, giuliamml commented on packages/client/src/users/addresses/__tests__/postUserAddress.test.ts
> +import { address2, userId } from 'tests/__fixtures__/addresses';
yes, I think that makes sense. Will add the suggested change

2022-07-05 10:23 UTC, giuliamml commented on packages/client/src/users/addresses/__tests__/putUserAddress.test.ts
> +  const data = address1;
agree for this too

2022-07-05 13:54 UTC, dnamorim approved these changes

2022-07-06 13:20 UTC, boliveira approved these changes

2022-07-06 13:20 UTC, merged