feat(core): add commerce pages redux
Farfetch/blackout pull request #46
Opened 2021-11-30 16:36 UTC by joaoprcosta

## Description

This feature adds the commerce pages logic into contents redux, more specifically:

. Add action doGetCommercePages
. Update Content reducer
. Add ranking logic to contents utils

### Dependencies

None.

## Checklist

- [X] The commit message follows our guidelines
- [X] Tests for the respective changes have been added
- [X] The code is commented, particularly in hard-to-understand areas
- [X] The labels and/or milestones were added

## Disclaimer

By sending us your contributions, you are agreeing that your contribution is made subject to the terms of our [Contributor Ownership Statement](https://github.com/Farfetch/.github/blob/master/COS.md)

2021-12-02 09:41 UTC, vinicaval approved these changes

2021-12-02 10:19 UTC, nelsonleite approved these changes

2021-12-02 14:14 UTC, helderburato approved these changes

2021-12-03 09:37 UTC, richard190m requested changes

2021-12-03 16:25 UTC, joaoprcosta commented on packages/core/src/contents/redux/actions/__tests__/doGetCommercePages.test.js
> +      expect(getCommercePages).toHaveBeenCalledTimes(1);
Yes, because `getCommercePages`could be called many times and `toHaveBeenCalledWith`doesn't validate that.

2021-12-06 10:01 UTC, richard190m commented on packages/core/src/contents/redux/actions/__tests__/doGetCommercePages.test.js
> +      expect(getCommercePages).toHaveBeenCalledTimes(1);
Ok. Stay like that then

2021-12-06 10:02 UTC, richard190m approved these changes

2021-12-06 10:36 UTC, merged