(WIP) Fix(client|react|redux): rename locale selectors
Farfetch/blackout pull request #463
Opened 2022-08-16 11:18 UTC by giuliamml

- This renames some locale selectors and action in order to improve consistency.

- Changed `useCountryStateCities` methods to match the changed Selectors.

BREAKING CHANGE: The following action was renamed:
fetchCountryCities -> fetchCountryStateCities

The following selectors were renamed:
getCountryCitiesError -> getCountryStateCitiesError
areCountryCitiesLoading -> areCountryStateCitiesLoading
getCountryCities -> getCountryStateCities
areCountryCitiesFetched -> areCountryStateCitiesFetched

## Description

### Dependencies

## Checklist

- [ ] The commit message follows our guidelines
- [ ] Tests for the respective changes have been added
- [ ] The code is commented, particularly in hard-to-understand areas
- [ ] The labels and/or milestones were added

## Disclaimer

By sending us your contributions, you are agreeing that your contribution is made subject to the terms of our [Contributor Ownership Statement](https://github.com/Farfetch/.github/blob/master/COS.md)

2022-08-16 15:34 UTC, boliveira approved these changes

2022-08-17 15:59 UTC, jhairabreu requested changes

2022-08-17 15:59 UTC, jhairabreu commented on packages/redux/src/locale/reducer.ts
> +  action: ActionFetchCountryStateCities,
Shouldn't this be `AnyAction` as you did in https://github.com/Farfetch/blackout/pull/460 ?

2022-08-17 16:26 UTC, jhairabreu approved these changes

2022-08-23 16:44 UTC, merged