fix(client|redux|react): orders area fixes
Farfetch/blackout pull request #468
Opened 2022-08-26 11:00 UTC by boliveira

## Description

- This introduces a number of fixes/refactorings for the `orders` area:
  - Changed `getGuestOrders` client to drop support
  for the legacy endpoint.
  - Added missing `fetchGuestOrders` action.
  - Removed `getGuestOrder` client as it is replaced by
  the `getOrder` client.
  - Added `getGuestOrderLegacy` and a corresponding action
   to add support for the retrieval of guest orders using
   the legacy endpoint to ease migration.
  - Refactored orders reducer to be easier to understand.
  - Renamed `getOrders` client to `getUserOrders` and
  its corresponding action `fetchOrders` to
  `fetchUserOrders` to improve consistency.
- Changed clients which were still defined to use the
`legacy` endpoint to use the new endpoints.
- Fixed a lot of incorrect types.
- Renamed some subscriptions clients and actions.
- Renamed actions `fetchListing` to `fetchProductListing` and `fetchSet` to
`fetchProductSet`.
- Renamed `getUserCredit` client to `getUserCredits`.

BREAKING CHANGE: The following exports were renamed:
- OrderStatus -> MerchantOrderStatus
- deleteRecipientFromTopic -> deleteSubscriptionTopicRecipient
- getOrders -> getUserOrders
- getUserCredit (client) -> getUserCredits
- clearAllUnsubscribeRecipientFromTopic -> clearAllUnsubscribeSubscriptionTopicRecipientRequests
- clearUnsubscribeRecipientFromTopic -> clearUnsubscribeSubscriptionTopicRecipientRequest
- fetchListing -> fetchProductListing
- fetchListingFactory -> fetchProductListingFactory
- fetchOrders -> fetchUserOrders
- fetchOrdersFactory -> fetchUserOrdersFactory
- fetchSet -> fetchProductSet
- fetchSetFactory -> fetchProductSetFactory
- fetchUserCredit -> fetchUserCredits
- getMerchantsFromOrder -> getOrderMerchants
- getReturnOptionsFromOrder -> getOrderReturnOptions
- getUserCredit (selector) -> getUserCredits
- unsubscribeFromSubscription -> unsubscribeSubscription
- unsubscribeFromSubscriptionFactory -> unsubscribeSubscriptionFactory
- unsubscribeRecipientFromTopic -> unsubscribeSubscriptionTopicRecipient
- unsubscribeRecipientFromTopicFactory -> unsubscribeSubscriptionTopicRecipientFactory

### Dependencies

## Checklist

- [X] The commit message follows our guidelines
- [X] Tests for the respective changes have been added
- [X] The code is commented, particularly in hard-to-understand areas
- [X] The labels and/or milestones were added

## Disclaimer

By sending us your contributions, you are agreeing that your contribution is made subject to the terms of our [Contributor Ownership Statement](https://github.com/Farfetch/.github/blob/master/COS.md)

2022-08-30 15:10 UTC, jhairabreu requested changes
TS issues on the client package were recently addressed, so i ask you to double check if all of these changes didn't cause any new TS issues (in the client package). Please check it out before merging this. thanks! 🙂

2022-08-30 17:10 UTC, boliveira commented on packages/client/src/orders/types/getUserOrders.types.ts
> +) => Promise<Orders>;
Yes, I have missed that. Just updated, can you check, please? Thank you!

2022-08-30 17:11 UTC, boliveira commented on packages/client/src/orders/__tests__/getUserOrders.test.ts
> +    await expect(getUserOrders(userId)).resolves.toEqual(mockOrdersResponse);
Fixed the mocks to be compliant with the types expected by this test. Can you take a look at it, please? Thank you!

2022-08-30 17:11 UTC, boliveira commented on packages/client/src/orders/getGuestOrderLegacy.ts
> +import { adaptError } from '../helpers/client/formatError';
Added a test for this client which I missed, thank you for alerting me! Can you check, please?

2022-08-31 08:47 UTC, jhairabreu approved these changes

2022-09-01 08:58 UTC, giuliamml approved these changes

2022-09-02 18:28 UTC, merged