fix(react): update handleSize function on the useBagItem
Farfetch/blackout pull request #47
Opened 2021-11-30 16:52 UTC by CatarinaCouto

## Description

This prevents the handleSize function from updating a size and adding the same size after. This happens because when
the previous bag quantity is bigger than the merchant quantity for the size change, the function `handleAddOrUpdateBagItem` is called with all the merchants of the size, instead of being called with all the merchants, except the one that is updated previously.

### Dependencies

None.

## Checklist

- [x] The commit message follows our guidelines
- [x] Tests for the respective changes have been added
- [x] The code is commented, particularly in hard-to-understand areas
- [x] The labels and/or milestones were added

## Disclaimer

By sending us your contributions, you are agreeing that your contribution is made subject to the terms of our [Contributor Ownership Statement](https://github.com/Farfetch/.github/blob/master/COS.md)

2021-11-30 17:08 UTC, anapim approved these changes

2021-11-30 19:35 UTC, helderburato commented
@boliveira could you give a check to this PR? Something is broken in the pipeline.

2021-11-30 20:32 UTC, boliveira commented
> @boliveira could you give a check to this PR? Something is broken in the pipeline.

This needs a rebase with `next` to catch the latest changes to the pipeline that include the fix.

2021-12-02 09:34 UTC, nelsonleite requested changes

2021-12-02 09:34 UTC, nelsonleite commented on packages/react/src/bags/hooks/useBagItem.ts
> + * check the [respective issue](https://gitlab.fftech.info/fps/platform/box/issues/160).
Please revert this change

2021-12-02 09:37 UTC, catarinacouto commented on packages/react/src/bags/hooks/useBagItem.ts
> + * check the [respective issue](https://gitlab.fftech.info/fps/platform/box/issues/160).
Applied ✅

2021-12-02 09:39 UTC, nelsonleite approved these changes

2021-12-02 09:40 UTC, helderburato approved these changes

2021-12-02 10:15 UTC, gabrielfmp approved these changes

2021-12-02 10:44 UTC, merged