fix(react): remove `useAction` from public exports
Farfetch/blackout pull request #500
Opened 2022-09-19 14:41 UTC by boliveira

## Description

- This removes the `useAction` module from the public exports
of the react package as it is an internal helper module and
was requiring the installation of the redux package even when
not importing this module specifically (ex: importing another
module from the package root).

BREAKING CHANGE: `useAction` hook is not available from
react package. Use `useDispatch` hook from `react-redux` directly instead.

### Dependencies

## Checklist

- [X] The commit message follows our guidelines
- [X] Tests for the respective changes have been added
- [X] The code is commented, particularly in hard-to-understand areas
- [X] The labels and/or milestones were added

## Disclaimer

By sending us your contributions, you are agreeing that your contribution is made subject to the terms of our [Contributor Ownership Statement](https://github.com/Farfetch/.github/blob/master/COS.md)

2022-09-20 07:56 UTC, jhairabreu requested changes
Can you leave a link to the issue for this somewhere in the commit message?

other than that, looks good to me

2022-09-20 13:03 UTC, jhairabreu approved these changes

2022-09-20 14:26 UTC, giuliamml approved these changes

2022-09-21 16:58 UTC, catarinacouto approved these changes

2022-09-21 17:00 UTC, merged