feat(react): add useSocialLogin hook
Farfetch/blackout pull request #837
Opened 2023-08-04 09:38 UTC by jpklzm

## Description
This adds a new hook to handle social authentication

### Dependencies

## Checklist

- [x] The commit message follows our guidelines
- [x] Tests for the respective changes have been added
- [x] The code is commented, particularly in hard-to-understand areas
- [ ] The labels and/or milestones were added

## Disclaimer

By sending us your contributions, you are agreeing that your contribution is made subject to the terms of our [Contributor Ownership Statement](https://github.com/Farfetch/.github/blob/master/COS.md)

2023-08-08 15:34 UTC, paulohfera approved these changes
Approved

2023-08-08 17:15 UTC, ruifcnunes requested changes

2023-08-08 17:15 UTC, ruifcnunes commented on packages/react/src/authentication/hooks/useSocialLogin.ts
> +const actionTypes = {
Please separate this logic and place it on the redux package. Make sure to use the correct prefixes on each actionType.

2023-08-08 17:15 UTC, ruifcnunes commented on packages/react/src/authentication/hooks/useSocialLogin.ts
> +type State = {
Same as above.

2023-08-08 17:15 UTC, ruifcnunes commented on packages/react/src/authentication/hooks/useSocialLogin.ts
> +  result?: object;
Can this type be more explicit? do we know what is the structure of the result?

2023-08-08 17:15 UTC, ruifcnunes commented on packages/react/src/authentication/hooks/useSocialLogin.ts
> +function reducer(state: State, action: Action) {
Please move this logic to the redux package as well (applies to all redux logic).

2023-08-08 17:15 UTC, ruifcnunes commented on packages/react/src/authentication/hooks/useSocialLogin.ts
> +        currentRequestId: action.meta.requestId,
Will we need to manage/store data for more than one request? Should we consider having a `result` property as an object where each result is keyed by its requestId?

something like:
```
result = {
 [action.meta.requestId]: actualResultForTheRequestId
}
```

(same would apply for isLoading and error properties, so we could control them per request).

2023-08-08 17:15 UTC, ruifcnunes commented on packages/react/src/authentication/hooks/useSocialLogin.ts
> +  payload: object;
Can this type be more explicit?

2023-08-08 17:15 UTC, ruifcnunes commented on packages/react/src/authentication/hooks/useSocialLogin.ts
> +  payload: object;
same as above

2023-08-31 09:42 UTC, ruifcnunes commented on packages/react/src/authentication/hooks/__tests__/useSocialLogin.test.tsx
> +  it('should return correctly with initial state and call all hook dependencies with the correct options', () => {
Can this test description be reviewed, please? 
This hook does not have other hook dependencies (apart from `useAction`) and you're expecting that nothing gets called at this point.

2023-08-31 10:02 UTC, ruifcnunes commented on packages/react/src/authentication/hooks/__tests__/useSocialLogin.test.tsx
> +        const current = getRenderedHook(mockInitialState);
Can we also have a test where we actually pass in a config for the client call, please?

2023-08-31 10:02 UTC, ruifcnunes commented on packages/react/src/authentication/hooks/__tests__/useSocialLogin.test.tsx
> +      it('should call `useSocialLogin` accountLink action without config', async () => {
same as https://github.com/Farfetch/blackout/pull/837/files#r1311398368

2023-09-05 09:21 UTC, pedro-gbf commented on packages/react/src/authentication/hooks/useSocialLogin.ts
> +      accountLink,
I would change name of the function to better indicate the action to be performed, `createAccountLink` is more indicative than simply `accountLink`, just a suggestion if you disagree you can close this thread.

2023-09-05 09:32 UTC, pedro-gbf approved these changes

2023-09-07 10:44 UTC, ruifcnunes approved these changes

2023-09-07 10:44 UTC, merged