docs: add new query parameters contents
Farfetch/blackout pull request #85
Opened 2021-12-15 16:02 UTC by joaoprcosta

## Description

More query parameters listed on search contents endpoint documentation
- target
- metadataCustom
- metadataSearchTagsValues
- 

### Dependencies

None.

## Checklist

- [X] The commit message follows our guidelines
- [ ] Tests for the respective changes have been added
- [X] The code is commented, particularly in hard-to-understand areas
- [X] The labels and/or milestones were added

## Disclaimer

By sending us your contributions, you are agreeing that your contribution is made subject to the terms of our [Contributor Ownership Statement](https://github.com/Farfetch/.github/blob/master/COS.md)

2021-12-15 16:26 UTC, richard190m requested changes

2021-12-15 16:26 UTC, richard190m commented on packages/client/src/contents/getSearchContents.ts
> + * @param {QueryTarget} [query.target] - The targets and respective values that a content type is configured (contentzone:ROW | country:GB | language:en-GB | benefits:test).
Maybe the example should be `{contentzone: ROW}` and the other examples, included in QueryTarget type definition above.

2021-12-15 17:08 UTC, vinicaval approved these changes

2021-12-22 16:43 UTC, richard190m approved these changes

2021-12-27 17:16 UTC, merged